Vagrant.configure("2") do |config|
    config.vm.box = 'centos/7'
    config.vm.hostname = 'manager'
    config.vm.network "private_network", ip: "192.168.1.2"
    config.vm.provider 'virtualbox' do |v| 
      v.memory =2048
    end
    
  end