Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.hostname = "db01"
    config.vm.network "private_network", ip: "192.168.1.4"
    config.vm.network "forwarded_port", guest: 3306, host: 3306
    config.vm.provision "shell", path: "provision.sh"
  end